[package]
name = "violet"
version = "0.0.1"
edition = "2021"
authors = ["Tei Roberts"]
description = "Retained mode GUI library"
readme = "README.md"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/violet"
repository = "https://github.com/ten3roberts/violet"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flax = { git = "https://github.com/ten3roberts/flax", version = "0.4.0", features = [
    "derive",
] }

glam = { version = "0.24", features = ["bytemuck"] }
futures = "0.3"
flume = "0.10"
parking_lot = "0.12"
slotmap = "1.0"
anyhow = "1.0"
once_cell = "1.18"
ulid = "1.0"

bytemuck = { version = "1.13", features = ["derive"] }
winit = "0.28"
wgpu = { version = "0.16" }
palette = { version = "0.7", features = [] }
dashmap = "5.4"
image = "0.24"

tracing-subscriber = { version = "0.3", features = [
    "parking_lot",
    "env-filter",
] }
tracing = "0.1"
pin-project = "1.1"

[profile.dev.package.image]
opt-level = 2
